routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');
Route::get('/wp-update', 'HomeController@updateFromWP');
Route::get('/{slug}', 'HomeController@show')->name('post.show');
Route::get('/tag/{slug}', 'HomeController@tag')->name('tag.show');
Route::get('/category/{slug}', 'HomeController@category')->name('category.show');
Route::get('/date/{date}', 'HomeController@showDate');
Route::post('newsletter/subscribe_request', 'NewsletterController@storeRequest');
Route::post('ckeditor/image_upload', 'Admin\CKEditorController@upload')->name('upload');
//Route::get('/verify/{token}', 'SubsController@verify');

Route::group(['middleware' => 'auth'], function(){
    Route::get('/logout', 'AuthController@logout');
//    Route::get('/profile', 'ProfileController@index');
//    Route::post('/profile', 'ProfileController@store');
    //Route::post('/comment', 'CommentsController@store');
});


Route::group(['prefix' => 'cms', 'middleware' => 'guest'], function(){
//    Route::get('/register', 'AuthController@registerForm');
//    Route::post('/register', 'AuthController@register');

    Route::get('/login', 'AuthController@loginForm')->name('login');
    Route::post('/login', 'AuthController@login');
});




Route::group(['prefix' => 'haifa-cms', 'middleware' => 'admin', 'namespace' => 'Admin'], function (){
    Route::get('/index', 'DashboardController@index')-> name('dashboard');
//    Route::get('/comments', 'CommentsController@index')->name('comments.index');
//    Route::get('/comments/toggle/{id}', 'CommentsController@toggle');

    Route::resource('/categories', 'CategoriesController');
    Route::resource('/tags', 'TagsController');
    Route::resource('/ads', 'AdsController');
    Route::resource('/users', 'UsersController');
    Route::resource('/posts', 'PostsController');
//    Route::resource('/subscribers','SubscribersController');

//    Route::delete('/comments/{id}/destroy', 'CommentsController@destroy')->name('comments.destroy');

});

Route::group(['prefix' => 'haifa-cms/settings', 'middleware' => 'admin', 'namespace' => 'Admin'], function (){
    Route::get('/index', 'SettingController@index')->name('settings');
    Route::get('/home', 'SettingController@homePageSettings')->name('settings.home');
    Route::get('/adv', 'SettingController@advSettings')->name('settings.adv');
    Route::put('/store-home-settings', 'SettingController@storeHomeSettings')->name('settings.store.home');
    Route::post('/store-adv-settings', 'SettingController@storeAdvSettings')->name('settings.adv.home');
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

//Auth::routes();

resources/views/admin/_sidebar.blade.php
<div class="sidebar">
    <!-- Sidebar Menu -->
    <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-book-open"></i>
                    <p>
                        Публикации
                        <i class="fas fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview" style="display: none;">
                    <li class="nav-item">
                        <a href="{{route('posts.create')}}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Новая публикация</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('posts.index')}}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Список публикаций</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-folder"></i>
                    <p>
                        Категории
                        <i class="fas fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview" style="display: none;">
                    <li class="nav-item">
                        <a href="{{route('categories.create')}}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Новая категория</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('categories.index')}}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Список категорий</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-folder"></i>
                    <p>
                        Теги
                        <i class="fas fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview" style="display: none;">
                    <li class="nav-item">
                        <a href="{{route('tags.create')}}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Новый тег</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('tags.index')}}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Список тегов</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item has-treeview">
                <a href="#" class="nav-link">
                    <i class="nav-icon fas fa-folder"></i>
                    <p>
                        Рекламные блоки
                        <i class="fas fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview" style="display: none;">
                    <li class="nav-item">
                        <a href="{{route('ads.create')}}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Новый блок</p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('ads.index')}}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Список блоков</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item has-treeview">
                <a href="{{route('settings')}}" class="nav-link">
                    <i class="nav-icon fas fa-folder"></i>
                    <p>
                        Настройки
                        <i class="fas fa-angle-left right"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview" style="display: none;">
                    <li class="nav-item">
                        <a href="{{route('settings.home')}}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Главная страница</p>
                        </a>
                        <a href="{{route('settings.adv')}}" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>Рекламные блоки</p>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a href="/filemanager?type=image" target="_blank" class="nav-link">
                    <i class="nav-icon fas fa-folder"></i>
                    <p>Файлы</p>
                </a>
            </li>
        </ul>
    </nav>
    <!-- /.sidebar-menu -->
</div>

resources/views/admin/errors.blade.php
@if($errors->any())
    @foreach($errors->all() as $error)
        <div class="alert alert-danger alert-dismissible">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <h5><i class="icon fas fa-ban"></i> Ошибка</h5>
            {{ $error }}
        </div>
    @endforeach
@endif

resources/views/admin/index.blade.php
@extends('layouts.admin')

@section('content')

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Haifaru CMS</h1>
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">General Form</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>
    </div>

@endsection